dist: xenial
language: python
sudo: false
env:
  - PYTHON_VERSION=3.6 COVER_PACKAGE="qp_fastp_minimap2"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  # installing qiita environment
  - conda config --add channels anaconda
  - conda config --add channels conda-forge
  - travis_retry conda create -q --yes -n qiita python=3.6 pip libgfortran numpy nginx cython
  - source activate qiita
  - pip install sphinx sphinx-bootstrap-theme coveralls
  - pip install https://github.com/biocore/qiita/archive/dev.zip --no-binary redbiom
  - sed 's/PORT = 7777/PORT = 6379/g' ${HOME}/miniconda3/envs/qiita/lib/python3.6/site-packages/qiita_core/support_files/config_test.cfg > config_test.cfg
  - export QIITA_CONFIG_FP=${PWD}/config_test.cfg
  # starting nginx
  - mkdir /home/travis/miniconda3/envs/qiita/var/run/nginx/
  - wget https://github.com/biocore/qiita/archive/dev.zip -O qiita-dev.zip
  - unzip qiita-dev.zip
  - nginx -c ${PWD}/qiita-dev/qiita_pet/nginx_example.conf
  - qiita-env make --no-load-ontologies
  - source deactivate
  # installing fastp-minimap2
  - conda config --add channels bioconda
  - conda create --yes -n qp-fastp-minimap2 -c bioconda samtools=1.11 minimap2 fastp python=3.6
  - source activate qp-fastp-minimap2
  - export QIITA_SERVER_CERT=$HOME/miniconda3/envs/qiita/lib/python3.6/site-packages/qiita_core/support_files/server.crt
  - export QC_REFERENCE_DB=$PWD/qp_fastp_minimap2/support_files/databases/
  - for file in $(ls $QC_REFERENCE_DB/*.gz); do gunzip $file; done
  - pip install flake8
  - pip install .
  # making sure we have the correct software versions
  - samtools_version=`samtools --version`
  - minimap2_version=`minimap2 --version`
  - fastp_version=$(fastp --version 2>&1)
  - if [[ $samtools_version != *"1.11"* ]]; then echo "wrong samtools version", $samtools_version; exit 1; fi
  - if [[ $minimap2_version != *"2.17"* ]]; then echo "wrong minimap2 version", $minimap2_version; exit 1; fi
  - if [[ $fastp_version != *"20.1"* ]]; then echo "wrong fastp version", $fastp_version; exit 1; fi
  - configure_qp_fastp_minimap2 --env-script 'source ~/.bash_profile; source activate qp-fastp-minimap2; export QC_REFERENCE_DB=$PWD/qp_fastp_minimap2/support_files/databases/' --server-cert $QIITA_SERVER_CERT
before_script:
  - source activate qiita
  - qiita plugins update
  - supervisord -c ${PWD}/qiita-dev/qiita_pet/supervisor_example.conf
  - sleep 10 # give enough time to the webserver to start
  - cat /tmp/supervisord.log
script:
  - source activate qp-fastp-minimap2
  - travis_wait 40 nosetests $COVER_PACKAGE --with-doctest --with-coverage -vv --cover-package=$COVER_PACKAGE
  - flake8 qp_fastp_minimap2 setup.py scripts/*
addons:
  postgresql: "9.5"
services:
  - redis-server
  - postgresql
after_success:
  - codecov
  - qiita-env drop
after_failure:
  - kill $QIITA_PID
  - qiita-env drop
